[package]
name = "stained"
version = "0.1.5"
authors = ["CJ Carey <perimosocordiae@gmail.com>"]
edition = "2024"

[lib]
name = "stained"

[dependencies]
rand = "0.9"
serde = { version = "1", features = ["derive"] }
